name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install and build
      run: |
        npm install
        npm run pBuild

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
